### ISSUE TITLE
missing import? 

### ISSUE THREAD

**Issue by gdreich** [GeoNode/geonode-oauth-toolkit#1]
hi,

I noticed an issue while trying to install geonode master branch. there is either a missing import in views/base.py (OAuth2ResponseRedirect) or [this line](https://github.com/GeoNode/geonode-oauth-toolkit/blob/7dd8b2247fe97f656765017f24860fce3421944b/oauth2_provider/views/base.py#L64) needs to be updated to use HttpResponseUriRedirect I think?

cheers

**Comment by afabiani** [comment]
@gdreich taking a look. Thanks for highlighting.
