### ISSUE TITLE
Bearer auth not working

### ISSUE THREAD

**Issue by vikipha** [GeoNode/geonode-oauth-toolkit#4]
Hi,

in commit https://github.com/GeoNode/geonode-oauth-toolkit/commit/e904a259d7b2d7a0da8aab0b1709a381b7870deb  you added some pre-check of request. But unfortunately it prevents Bearer authentication to pass. You are Comparing Authorization header value to "Bearer" with ==, but This header typically contains "Bearer <token>" so comparison always fail.
Could you please fix it and make release, i don't want to maintain fork :-) 

thanks,

Viktor

**Comment by afabiani** [comment]
Fixed by https://github.com/GeoNode/geonode-oauth-toolkit/pull/5

**Comment by vikipha** [comment]
Hi, could you please make release containing this fix? Thanks. Viktor

**Comment by afabiani** [comment]
@vikipha sure, I'm going to make final releases soon this week

**Comment by vikipha** [comment]
Great, thanks! :-)

**Comment by vikipha** [comment]
Hi Allesio, 

I know it's not the best time. But I am still looking forward to release containing that fix.
Could you please make a release?

Thanks,

Viktor

**Comment by afabiani** [comment]
@vikipha sorry I completely forgot

https://github.com/GeoNode/geonode-oauth-toolkit/releases/tag/1.1.5.1
